services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: url-shortener-api

    ports:
      - "3000:3000"

    env_file:
      - .env

    restart: unless-stopped